### ISSUE TITLE
das-schiff vs Gardener vs Rancher

### ISSUE THREAD

**Issue by dominikmeyersap** [telekom/das-schiff#10]
I heard you on [kubernetespodcast](https://kubernetespodcast.com/episode/158-telekom-with-a-k/) and I couldn't help to wonder.

What you do covers exactly what Gardener and Rancher do... What is the USP? It was not mentioned in the Podcast (or I missed it during 🏋️ ).

Would be interested to learn more!

**Comment by schrej** [comment]
The focus of Das Schiff is on independence of the created clusters. They can operate completely on their own, even if the entire Schiff Control Plane (running CAPI etc.) is unavailable. 
Gardener (and also Kubermatic) run the control planes of the deployed clusters in one or more management clusters, so the created clusters aren't independent.

As far as I'm aware Rancher also doesn't have automated provisioning for bare metal hosts, which is something we need.
