### ISSUE TITLE
How do you provision the first cluster where Das Schiff is running?

### ISSUE THREAD

**Issue by earthquakesan** [telekom/das-schiff#9]
Hello!

Das Schiff is awesome project, there is a question though on how to setup the initial k8s cluster, where Das Schiff will be running. Do you simply use managed k8s (e.g. EKS)?

**Comment by MaxRink** [comment]
Hi, 

that is also a CAPI-based cluster. We usually start with a KIND cluster somewhere (Bastion host, local laptop), crete the mgmt cluster and then pivot that over so the mgmt cluster controls itself

**Comment by earthquakesan** [comment]
@MaxRink thanks a lot for the fast reply! -)
